server:
  port: 8081
spring:
  application:
    name: service-hi
eureka:
  client:
    service-url:
#      defaultZone: http://29.20.23.184:31001/eureka/
      defaultZone: http://localhost:8080/eureka